name: Build and Upload Release Package

on:
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 签出仓库
        uses: actions/checkout@v4

      - name: 设置发行标签
        id: vars
        run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: 准备目录结构
        run: |
          mkdir oauth-oidc
          shopt -s dotglob
          mv !(oauth-oidc) oauth-oidc/

      - name: 打包ZIP
        run: |
          zip -r "OAuth-OIDC_${{ steps.vars.outputs.tag }}.zip" oauth-oidc

      - name: 上传发行版资产
        uses: softprops/action-gh-release@v2
        with:
          files: "OAuth-OIDC_${{ steps.vars.outputs.tag }}.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
